<a href="https://colab.research.google.com/github/mateusparanhos/892-ADA/blob/main/Atividade_4_Plotly.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Atividade

Resolver as questões abaixo. Em seguida, criar um repositório público no GitHub e armazenar no notebook criado, enviando somente o link do NOTEBOOK para o [Formulário](https://docs.google.com/forms/d/e/1FAIpQLSf8IUCLt4kowhHhB3SRQofE2I8NuXuDadBYjRHqUxgb3yWOaQ/viewform).

In [12]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px


#### Questão 1

Criar 2 vetores, um com uma série historica de anos de 1970 até 2022 e um segundo vetor com a mesma quantidade de observações e números inteiros aleatórios variando de 1 a 20000. Em seguida montar um gráfico com a melhor visualização para os dados com a biblioteca Plotly Express.

In [13]:
anos = np.arange(1970,2023)
anos

array([1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980,
       1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
       1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022])

In [20]:
valores = np.random.randint(1, 20001, len(anos))
valores

array([19420,  8655, 14695,  4215, 11080,  3557,  9921,  7518,  3582,
        9315, 15248, 12280,  3835, 16758,  6763,  9520,  9216,  1016,
        2373, 17948, 19718,  7124, 13526, 13891, 19040, 16233,  2927,
       15177,  6290,  9880, 16434,  2845,  5975,  4576, 10175,  8637,
       13323, 18482,  1765,   492,  7891,  1905,  1677, 16907, 10872,
       11933,   125,  2495, 16097,  4261, 10956,  3697, 17404])

In [21]:
px.line(x=anos, y=valores)

#### Questão 2

Criar uma lista com as letras do alfabeto, depois um vetor com a mesma quantidade de observações e números inteiros aleatórios variando de 10 a 100. Em seguida montar um gráfico com a melhor visualização para os dados com a biblioteca Plotly Express.

Utilize o objeto string para resolver a questão:

```
import string
string.ascii_lowercase
```

In [25]:
import string 
letras = list(string.ascii_lowercase)
letras


['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [26]:
num=np.random.randint(10,101, len(letras))
num 

array([77, 87, 69, 88, 95, 72, 69, 16, 87, 98, 42, 90, 55, 73, 84, 38, 48,
       92, 42, 60, 67, 63, 10, 25, 83, 99])

In [28]:
px.bar(x=letras, y=num, text=num, color=letras)

#### Questão 3

Criar 2 vetores com a mesma quantidade de observações, 500 registros , de números inteiros aleatórios, o primeiro variando de 1000 a 2000, o segundo variando de 5000 a 10000. Em seguida montar um gráfico com a melhor visualização para os dados com a biblioteca Plotly Express, demonstrando relação entre as variáveis.

In [30]:
arr1 = np.random.randint(1000,2001,500)
arr2 = np.random.randint(5000,10001,500)

In [31]:
px.scatter(x=arr1, y=arr2)

#### Questão 4

Criar uma vetor com 500 registros de números inteiros variando entre 125 e 857. Em seguida montar um gráfico que mostre a dispersão com a melhor visualização para os dados com a biblioteca Plotly Express.

In [32]:
vet = np.random.randint(125,858,500)

In [33]:
px.histogram(x=vet)

In [34]:
px.box(y=vet)